# Julia Tutorial

Following [doggo dot jl's tutorial](https://www.youtube.com/watch?v=jA6IYSCpIug&list=PLhQ2JMBcfAsi76O13sJzk4LXA_mu5sd9E)

## 01x03 - Variables, Expressions, Memory, and Types

https://www.youtube.com/watch?v=J4DnzjIFj8w

In [59]:
x = 1
y = 2
z = x + y
println(z)

3


In [60]:
typeof(z)

Int64

In [61]:
typeof(NaN)

Float64

In [62]:
bitstring(0.1)

"0011111110111001100110011001100110011001100110011001100110011010"

In [63]:
typeof(-1//2)

Rational{Int64}

In [64]:
-1//2

-1//2

In [65]:
10^6

1000000

In [66]:
1_000_000

1000000

In [67]:
pi

π = 3.1415926535897...

In [68]:
println(sqrt(4))
println(cbrt(8))
println(convert(Int64, 3.0))
println(iseven(3))
println(isodd(4))
println(rem(5, 2))
println(5 % 2)
println(round(3.55, digits=1, RoundUp))
println(round(3.55, digits=1, RoundDown))

2.0
2.0
3
false
false
1
1
3.6
3.5


In [69]:
a = 3
b = 3.0
println(a == b)
println(a === b)

true
false


In [70]:
println(typeof('a'))
println(typeof("a"))

Char
String


In [71]:
α = 1
β = 2
println(α + β)

3


In [72]:
println(4 / 2)
println(div(4, 2))
println(4 ÷ 2)
println(√4)
println(∛8)

2.0
2
2
2.0
2.0


In [73]:
α = 3
⌚ = 2
γ = 4
println(√γ + α ÷ ⌚)

3.0


In [74]:
println(0.1 + 0.2 == 0.3)
println(0.1 + 0.2 ≈ 0.3)

false
true


In [75]:
H₂O = "water"

"water"

In [76]:
Char(65)

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [77]:
#= start of multiline comment
comment
comment
comment
=#

In [78]:
string = "Hello, world!"
println(string)

Hello, world!


In [79]:
println("""You can "quote" strings with triple quotes""")

You can "quote" strings with triple quotes


In [80]:
⛄ = "⛄"
println(⛄^5)

⛄⛄⛄⛄⛄


In [81]:
s1 = "Hello, "
s2 = "world!"
s3 = s1 * s2

"Hello, world!"

In [82]:
my_name = "Ryan"
println("Hello, my name is $my_name")

Hello, my name is Ryan


In [83]:
a = 1
b = 2
println("a + b = $(a + b)")

a + b = 3


In [84]:
# Seems like this is broken in jupyter notebooks?
# print("Enter text: ") ; input = readline()

In [85]:
number = "10"
number_int = parse(Int64, number)
println(typeof(number_int), " ", number)

Int64 10


In [86]:
color = :mycolor
typeof(color)

Symbol

In [87]:
s1 = "Hello, world!"
printstyled(s1, bold=true, color=:red)

Hello, world!

## 01x04 - Arrays, Tuples, & Dictionaries

https://www.youtube.com/watch?v=J4lljmTA7Pc

### Dictionaries

In [88]:
d = Dict()

Dict{Any, Any}()

In [89]:
d = Dict("A" => 1, "B" => 3, "C" => 5, "D" => 7)

Dict{String, Int64} with 4 entries:
  "B" => 3
  "A" => 1
  "C" => 5
  "D" => 7

In [90]:
d["A"]

1

In [91]:
d["A"] = 10
d

Dict{String, Int64} with 4 entries:
  "B" => 3
  "A" => 10
  "C" => 5
  "D" => 7

In [92]:
d2 = Dict("A" => 10, "B" => 30, "C" => 60, "D" => 50)
d3 = Dict("A" => 100, "E" => 150, "F" => 210)
println(keys(d2))
println(values(d2))

["B", "A", "C", "D"]
[30, 10, 60, 50]


In [93]:
merge(d2, d3)  # If conflict, prioritize last dict listed

Dict{String, Int64} with 6 entries:
  "B" => 30
  "A" => 100
  "C" => 60
  "D" => 50
  "E" => 150
  "F" => 210

In [94]:
push!(d2, "G" => 350)
pop!(d2, "B")
d2

Dict{String, Int64} with 4 entries:
  "A" => 10
  "C" => 60
  "D" => 50
  "G" => 350

In [95]:
"A" in keys(d2)

true

In [96]:
2 in values(d2)

false

In [97]:
dict_int = Dict(1 => "one", 2 => "two", 3 => "three")

Dict{Int64, String} with 3 entries:
  2 => "two"
  3 => "three"
  1 => "one"

In [98]:
println(dict_int[1])

one


### Tuples

In [99]:
tup = (1, 2, 3, "hi", 5, 6.0, 7)

(1, 2, 3, "hi", 5, 6.0, 7)

In [100]:
tup[1]

1

In [101]:
tup[2:end]

(2, 3, "hi", 5, 6.0, 7)

In [103]:
tup[1:2:5]

(1, 3, 5)

In [104]:
tp1 = (1, 2, 3)
tp2 = (4, 5, 6)
tp3 = (tp1, tp2)
println(tp3)
tp4 = (tp1..., tp2...)
println(tp4)

((1, 2, 3), (4, 5, 6))
(1, 2, 3, 4, 5, 6)


In [110]:
println(1 in tp4)
println(!(1 in tp4))
println(1 ∈ tp4)
println(1 ∉ tp4)

true
false
true
false


### Named Tuples

In [106]:
ntp = (word="doggo", num=3.14, sym=:red)
typeof(ntp)

NamedTuple{(:word, :num, :sym), Tuple{String, Float64, Symbol}}

In [107]:
ntp[1]
# This does not work:
# ntp[2:end]

"doggo"

In [112]:
println(ntp[:sym])
println(ntp.sym)

red
red


### Arrays

In [113]:
a = []

Any[]

In [114]:
column_vector = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [115]:
row_vector = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [119]:
rand_arr = rand(4, 2, 3)

4×2×3 Array{Float64, 3}:
[:, :, 1] =
 0.445217  0.477163
 0.498626  0.594645
 0.19609   0.556527
 0.211846  0.379313

[:, :, 2] =
 0.452269  0.985675
 0.895624  0.0019208
 0.543858  0.0331772
 0.390662  0.773667

[:, :, 3] =
 0.692425  0.049605
 0.398582  0.0970162
 0.119755  0.679346
 0.407315  0.61637

In [118]:
a = [1, 3.14, "dog", :red]
a[2]

3.14

In [121]:
m = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [122]:
m[1, 2]

2

In [123]:
m[:, 3]

3-element Vector{Int64}:
 3
 6
 9

In [124]:
m[2, :]

3-element Vector{Int64}:
 4
 5
 6

In [125]:
m[1:2, 2:3]

2×2 Matrix{Int64}:
 2  3
 5  6

In [126]:
m[end, :]

3-element Vector{Int64}:
 7
 8
 9

In [127]:
m[3]

7

In [129]:
size(m)

(3, 3)

In [130]:
length(m)

9

In [131]:
eltype(m)

Int64

In [132]:
minimum(m)

1

In [133]:
maximum(m)

9

In [134]:
extrema(m)

(1, 9)

In [135]:
transpose(m)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [136]:
m'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [138]:
fill(π, 5, 5)

5×5 Matrix{Irrational{:π}}:
 π  π  π  π  π
 π  π  π  π  π
 π  π  π  π  π
 π  π  π  π  π
 π  π  π  π  π

In [139]:
zeros(3, 5)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [140]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]
union(a, b)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [141]:
[a, b]

2-element Vector{Vector{Int64}}:
 [1, 2, 3, 4, 5]
 [6, 7, 8, 9, 10]

In [142]:
[a; b]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [143]:
[a b]

5×2 Matrix{Int64}:
 1   6
 2   7
 3   8
 4   9
 5  10